# Generated by Django 6.0.2 on 2026-02-21 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('year', models.PositiveSmallIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('horsepower', models.PositiveSmallIntegerField()),
                ('transmission', models.CharField(choices=[('M', 'Manual'), ('A', 'Auto')], max_length=10)),
                ('fuel_type', models.CharField(choices=[('P', 'Petrol'), ('D', 'Diesel'), ('H', 'Hybrid'), ('E', 'EV')], max_length=10)),
                ('image_url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.brand')),
                ('features', models.ManyToManyField(blank=True, to='catalog.feature')),
            ],
        ),
    ]
